wallpaper {
    monitor = eDP-1
    path = ~/Pictures/rainworld_wallpaper.jpg
    fit_mode = cover
}

#wallpaper {
#    monitor = HDMI-A-1
#    path = ~/Pictures/rainworld_wallpaper.jpg
#}
#
#wallpaper {
#    monitor = DP-3
#    path = ~/Pictures/rainworld_wallpaper6.jpg
#}
